// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApjyY1lgekxRbkZHMk37TD-HzwvQTgXE',
    appId: '1:672790987097:web:fde05724c743f35661cc48',
    messagingSenderId: '672790987097',
    projectId: 'rook2-94e65',
    authDomain: 'rook2-94e65.firebaseapp.com',
    storageBucket: 'rook2-94e65.appspot.com',
    measurementId: 'G-E49E13Y6P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ra5K1OBOGKbCT_rdQwDbEQIyuq8_8fg',
    appId: '1:672790987097:android:3d914883d217a41561cc48',
    messagingSenderId: '672790987097',
    projectId: 'rook2-94e65',
    storageBucket: 'rook2-94e65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAZ7oh6h1bRzOUesglfN69En4IyTUNEQ',
    appId: '1:672790987097:ios:4c8e06b8202026de61cc48',
    messagingSenderId: '672790987097',
    projectId: 'rook2-94e65',
    storageBucket: 'rook2-94e65.appspot.com',
    iosBundleId: 'com.divinetechs.dtlivetv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAZ7oh6h1bRzOUesglfN69En4IyTUNEQ',
    appId: '1:672790987097:ios:4c8e06b8202026de61cc48',
    messagingSenderId: '672790987097',
    projectId: 'rook2-94e65',
    storageBucket: 'rook2-94e65.appspot.com',
    iosBundleId: 'com.divinetechs.dtlivetv',
  );
}
